---
- name: restart apache
  command: apachectl restart
  register: restart_apache_out

- name: reload apache
  command: apachectl graceful
  when: restart_apache_out is not defined

- name: stop apache
  service: name=apache2 state=stopped
