---
- apt: pkg={{ item }}
  with_items:
    - vlan
    - bridge-utils

- name: 'Configure VXLAN to use IANA assigned port: 4789'
  copy: content="options vxlan udp_port=4789" dest=/etc/modprobe.d/vxlan-port.conf owner=root group=root mode=0644

- name: check if neutron user exists
  action: shell getent passwd neutron
  register: neutron_user
  ignore_errors: True
  changed_when: False

- name: neutron user
  user: name=neutron shell=/bin/false createhome=no
  when: neutron_user.rc == 0

- name: neutron user
  user: name=neutron comment=neutron shell=/bin/false system=yes home=/nonexistent createhome=no
  when: neutron_user.rc != 0

- name: neutron sudoer
  template: |
    src=etc/sudoers.d/neutron
    dest=/etc/sudoers.d/neutron
    owner=root
    group=root
    mode=0440

- name: get neutron source repo
  git: |
    repo={{ openstack.git_mirror }}/neutron.git
    dest=/opt/stack/neutron
    version={{ neutron.rev }}
    update=yes
  register: result
  until: result|success
  retries: 3
  delay: 60
  notify:
    - pip install neutron
    - neutron rootwrap
    - restart neutron services
- meta: flush_handlers

- file: dest=/etc/neutron state=directory
- file: dest=/etc/neutron/services/loadbalancer/haproxy state=directory
- file: dest=/var/lib/neutron state=directory owner=neutron
- file: dest=/var/cache/neutron state=directory mode=0700 owner=neutron group=neutron
- file: dest=/var/log/neutron state=directory mode=0755 owner=neutron group=neutron

- name: neutron config
  action: template src={{ item }} dest=/etc/neutron mode=0644
  with_fileglob: ../templates/etc/neutron/*
  notify:
     - restart neutron services

- fail: msg="Invalid Neutron plugin, must be either ml2 or ovs"
  when: neutron.plugin != 'ovs' and neutron.plugin != 'ml2'

- file: dest=/etc/neutron/plugins/ml2 state=directory
  when: neutron.plugin == 'ml2'

- template: |
    src=etc/neutron/plugins/ml2/ml2_plugin.ini
    dest=/etc/neutron/plugins/ml2/ml2_plugin.ini
    mode=0644
  when: neutron.plugin == 'ml2'
  notify:
    - restart neutron services

- file: dest=/etc/neutron/plugins/openvswitch state=directory
  when: neutron.plugin == 'ovs'

- template: |
    src=etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
    dest=/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
    mode=0644
  when: neutron.plugin == 'ovs'
  notify:
    - restart neutron services
