---
# Ensure this file is written before kvm_intel or kvm_amd module is loaded
- name: enable nested kvm
  template: src=etc/modprobe.d/kvm-nested.conf
            dest=/etc/modprobe.d/kvm-nested.conf owner=root group=root
            mode=0644

- name: install nova-compute packages
  action: apt pkg={{ item }}
  with_items:
    - libvirt-bin
    - python-libvirt
    - qemu-kvm
    - open-iscsi

- name: update various lines in libvirtd.conf
  lineinfile: dest=/etc/libvirt/libvirtd.conf regexp="{{ item.value.regexp }}"
              line="{{ item.value.line }}"
  notify: restart libvirt-bin
  with_dict:
    ltcp:
      regexp: '^listen_tcp\s*='
      line: "listen_tcp = 1"
    ltls:
      regexp: '^listen_tls\s*='
      line: "listen_tls = 0"
    atcp:
      regexp: '^auth_tcp\s*='
      line: "auth_tcp = \"none\""
    lvopts:
      regexp: '^libvirtd_opts'
      line: "libvirtd_opts=\"-d -l\""

- name: ensure kvm is supported by cpu and enabled in bios
  command: kvm-ok
  when: nova.libvirt_type|match('kvm$')
  changed_when: False

- name: shutdown default libvirt network is started
  shell: ip addr show virbr0 && virsh net-destroy default
  failed_when: False

- name: disable libvirt default network autostart
  file: dest=/etc/libvirt/qemu/networks/autostart/default.xml state=absent
