---
- name: fetch rados.py
  command: wget "{{ ceph.rados_url }}"
    args:
      chdir: /opt/openstack/current/cinder/lib/python2.7/site-packages/
      creates: /opt/openstack/current/cinder/lib/python2.7/site-packages/rados.py

- name: rados.py perms
  file:
    path: /opt/openstack/current/cinder/lib/python2.7/site-packages/rados.py
    owner: root
    group: root
    mode: 0644

- name: fetch rbd.py
  command: wget "{{ ceph.rbd_url }}"
    args:
      chdir: /opt/openstack/current/cinder/lib/python2.7/site-packages/
      creates: /opt/openstack/current/cinder/lib/python2.7/site-packages/rbd.py

- name: rbd.py perms
  file::
    path: /opt/openstack/current/cinder/lib/python2.7/site-packages/rbd.py
    owner: root
    group: root
    mode: 0644

- name: fetch cinder keyring
  slurp: path=/etc/ceph/ceph.client.cinder.keyring
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: cinder_keyring

- name: write cinder keyring
  copy:
    dest: "{{ cinder_keyring['source'] }}"
    content: "{{ cinder_keyring['content'] | b64decode }}"
    mode: 0644
    owner: cinder
    group: cinder

# used in cinder.conf
- name: fetch contents of uuid file
  slurp: path=/etc/ceph/cinder_uuid
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"
  register: cinder_uuid_file
