---
- name: check if cinder user exists
  shell: getent passwd cinder
  register: cinder_user
  failed_when: False
  changed_when: False

- name: cinder user
  user: name=cinder shell=/bin/false createhome=no
  when: cinder_user|success

- name: cinder user
  user: name=cinder comment=cinder shell=/bin/false system=yes
        home=/nonexistent createhome=no
  when: not cinder_user|success

- name: /etc/cinder
  file: dest=/etc/cinder state=directory

- name: cinder lib dirs
  file: dest={{ item }} state=directory owner=cinder group=cinder
  with_items:
    - /var/lib/cinder
    - /var/lib/cinder/images

- name: cinder private dirs
  file:
    dest: "{{ item }}"
    state: directory
    mode: 0700
    owner: cinder
    group: cinder
  with_items:
    - /var/cache/cinder
    - /var/lib/cinder/lock

- name: cinder log dir
  file: dest=/var/log/cinder state=directory mode=2750 owner=cinder group=adm

# needs to happen before 'cinder config'
- include: ceph_integration.yml
  when: ceph.enabled

- name: error out when swift haproxy vip is not updated
  fail: msg="swift haproxy vip needs to be updated for use with cinder backup"
  when: swift.enabled|bool and (endpoints.swift.haproxy_vip == fqdn)

- name: cinder config
  template: src={{ item }} dest=/etc/cinder mode=0640 owner=cinder group=cinder
  with_fileglob: ../templates/etc/cinder/*
  notify:
    - restart cinder services
    - restart cinder backup service

- name: cinder sudoer
  template: src=etc/sudoers.d/cinder dest=/etc/sudoers.d/cinder owner=root
            group=root mode=0440

- include: logging.yml
  tags:
    - logrotate
    - logging
