---
- name: configure rsyslog
  template: src={{ item }} dest=/etc/rsyslog.d mode=0644
  with_fileglob: ../templates/etc/rsyslog.d/*
  notify: restart rsyslog

- name: create logstash user
  user: name=logstash comment="Logstash Service User" shell=/sbin/nologin system=yes home=/var/lib/logstash

- name: install logstash-forwarder
  apt: pkg=logstash-forwarder
  when: logging.install_method == 'apt'

- name: stop logstash-forwarder service
  service:
    name: logstash-forwarder
    state: stopped
    enabled: yes
    must_exist: False
  register: lsfstop

- name: download logstash
  get_url: url={{ logging.download.url }}
           dest=/tmp/logstash-forwarder_{{ logging.version }}_amd64.deb
  when: logging.install_method == 'file'

- name: install logstash
  apt: deb=/tmp/logstash-forwarder_{{ logging.version }}_amd64.deb
  when: logging.install_method == 'file'

- name: install logstash-forwarder service
  template: src=etc/init/logstash-forwarder.conf dest=/etc/init/logstash-forwarder.conf mode=0644

- name: remove logstash-forwarder init.d
  file: dest=/etc/init.d/logstash-forwarder state=absent

- name: custom cert auth directory
  file: dest=/usr/local/share/ca-certificates state=directory mode=0755
  when: logging.forward.host and logging.forward.tls.enabled

- name: (possibly self-signed) ssl cert
  template: src=logging-forward.crt dest=/usr/local/share/ca-certificates/logging-forward.crt mode=0644
  notify:
    - refresh cert auths
    - restart logstash-forwarder
  when: logging.forward.host and logging.forward.tls.enabled

- name: logstash-forwarder config directory
  file: dest=/etc/logstash-forwarder.d state=directory mode=0755

- name: configure logstash-forwarder forwarding
  template: src=etc/logstash-forwarder.d/main.conf dest=/etc/logstash-forwarder.d/main.conf mode=0644
  notify: restart logstash-forwarder
  when: logging.forward.host

- meta: flush_handlers

- name: start and enable logstash-forwarder service
  service: name=logstash-forwarder state=started enabled=yes
