---
- name: ceph status check
  sensu_check: name=check-ceph-status plugin=check-ceph.rb
               use_sudo=true args='--criticality {{ ceph.monitoring.sensu_checks.check_ceph_status.criticality }} {{ ceph.monitoring.sensu_checks.check_ceph_status.escalate_flags }} -o -f -p'
  notify: restart sensu-client

- name: ceph cluster usage check
  sensu_check: name=check-ceph-cluster-usage plugin=check-ceph-usage.rb
               use_sudo=true args='--criticality {{ ceph.monitoring.sensu_checks.check_ceph_status.criticality }} -v'
               interval=300
  notify: restart sensu-client

- name: ceph sla metrics
  sensu_metrics_check: name=ceph-sla-metrics plugin=metrics-os-api.py
                       args='-S ceph --scheme {{ monitoring.graphite.host_prefix }}'
                       use_sudo=true
  notify: restart sensu-client

- name: ceph usage metrics
  sensu_metrics_check:
    name: ceph-usage-metrics
    plugin: metrics-ceph.py
  notify: restart sensu-client
