---
glance:
  rev: fd4a8b9cab7c92b9f7a4a3077206f119789f3162
  api_workers: 5
  sync:
    enabled: true
    listening_port: 25307
    download_limit: 0
    upload_limit: 0
    folder_rescan_interval: 600
    storage_path: /var/lib/btsync
    device_name: image-cache
    dir: /var/lib/glance/images
