---
- name: install docker-registry apt dependencies
  apt: pkg={{item}}
  with_items:
    - liblzma-dev
    - libevent-dev
  when: docker.enabled

- name: get docker-registry source repo
  git: |
    repo={{ docker.registry.repourl }}
    dest=/opt/docker-registry
    version={{ docker.registry.rev }}
  register: result
  until: result|success
  retries: 3
  delay: 60
  notify:
    - create docker-registry virtualenv
    - install docker-registry
  when: docker.enabled
- meta: flush_handlers

- name: /etc/docker-registry
  file: dest=/etc/docker-registry state=directory
  when: docker.enabled

- name: docker-registry configuration
  template: src=etc/docker-registry/config.yml dest=/etc/docker-registry/config.yml mode=0644
  notify:
    - restart docker-registry
  when: docker.enabled

- name: docker-registry upstart
  template: src=etc/init/docker-registry.conf dest=/etc/init/docker-registry.conf mode=0644
  notify:
    - restart docker-registry
  when: docker.enabled
