---
- name: Check if keystone user exists
  action: shell getent passwd keystone
  register: keystone_user
  failed_when: False
  changed_when: False

- name: keystone user
  user: name=keystone shell=/bin/false createhome=no
  when: keystone_user|success

- name: keystone user
  user: name=keystone comment=keystone shell=/bin/false system=yes
        home=/nonexistent createhome=no
  when: not keystone_user|success

- name: WORKAROUND - keystone does not include babel in dependencies
  pip: name=babel

- name: get keystone source repo
  git: repo={{ openstack.git_mirror }}/keystone.git
       dest=/opt/stack/keystone
       version={{ keystone.rev }}
       update={{ openstack.git_update }}
  register: result
  until: result|success
  retries: 3
  delay: 60
  notify:
    - pip install keystone
    - restart keystone services

- meta: flush_handlers

- name: keystone config dir
  file: dest=/etc/keystone state=directory

- name: keystone log dir
  file: dest=/var/log/keystone state=directory mode=0755 owner=keystone
        group=keystone

- name: install keystone service
  upstart_service: name=keystone user=keystone cmd=/usr/local/bin/keystone-all
                   config_dirs=/etc/keystone

- name: configure keystone
  template: src={{ item }} dest=/etc/keystone/ mode=0644
  with_fileglob: ../templates/etc/keystone/*
  notify:
    - restart keystone services

- name: start keystone
  service: name=keystone state=started

- name: permit access to keystone
  command: ufw allow {{ item }}/tcp
  with_items:
    - 5001
    - 35358

- name: add cron job to clean up expired tokens
  template: src=etc/cron.hourly/drop-expired-keystone-tokens
            dest=/etc/cron.hourly/drop-expired-keystone-tokens
            owner=root group=root mode=0755
