---
- name: check nova
  shell: "curl -I --connect-timeout 2 {{ fqdn }}:{{ endpoints[item].port.haproxy_api }}{{ '/' + endpoints[item].version|default('') }}"
  with_items:
    - glance
    - keystone
    - neutron
    - nova
