---
neutron:
  rev: 42be50d7e43a25e8b7f7f5f0a2f526bc38d6c2e3
  api_workers: 3
  agent_down_time: 20
  report_interval: 4
  dhcp_dns_servers:
    - 8.8.8.8
    - 8.8.4.4
  service_plugins:
    - neutron.services.l3_router.l3_router_plugin.L3RouterPlugin
