---
- name: upgrade cinder control
  hosts: controller
  max_fail_percentage: 1
  tags:
    - cinder
    - cinder-control

  pre_tasks:
    - name: dump cinder db
      mysql_db:
        name: cinder
        state: dump
        target: /backup/cinder-preupgrade.sql
      run_once: True
      tags: dbdump
      delegate_to: "{{ groups['db'][0] }}"

  roles:
    - role: cinder-control
      force_sync: true
      restart: True
      database_create:
        changed: false
  environment: "{{ env_vars|default({}) }}"

- name: upgrade cinder data software
  hosts: cinder_volume
  max_fail_percentage: 1
  tags:
    - cinder
    - cinder-volume

  roles:
    - role: cinder-data
      restart: True
  environment: "{{ env_vars|default({}) }}"
